"""empty message

Revision ID: 5947bb9215f7
Revises: ae7934ce1e59
Create Date: 2022-08-05 04:15:09.480494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5947bb9215f7'
down_revision = 'ae7934ce1e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('administrator', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'administrator')
    # ### end Alembic commands ###
